### ISSUE TITLE
3 Additional models’ questions

### ISSUE THREAD

**Issue by rntdev1** [thawro/web-object-detector#1]
Hi! I have my own YOLOv8 ONNX-exported model. It is only one, but looks like you used 3 more. So, can I use the NMS model (or how do I get my own one) and why did you make entire 2 new models just for something that can be made with a simple algorithm? Kind regards, - Remote

**Comment by thawro** [comment]
Hello, the 3 other „models” are needed because ONNX model exported from YOLOv8 doesnt include the **preprocessing** (image scaling and/or padding to exact size), **NMS** and **postprocessing** (inverse of preprocessing for results). 

Well, of course you can implement those operations simply in JS, but I wanted to make it easilly work with other programming languages (thats why ONNX is used) and to enable a simple pipeline workflow.

The other models are placed [here](https://github.com/thawro/web-object-detector/tree/5968ce13d340a1bd7654af04bbe2754e019a6e96/web-object-detector/src/assets/onnx).

Hope that this helps with your concern.

**Comment by rntdev1** [comment]
Thanks. For anyone else wandering, I used [this NMS model generator](https://github.com/Hyuto/fun/blob/master/test-onnx-graph-surgeon/nms-onnx-v8.py). Also I stole preprocessing function from same guy.

**Comment by thawro** [comment]
Btw, the python code for the creation of pre/post processing onnx models is in [my other repo](https://github.com/thawro/yolov8-digits-detection/tree/b73467a263f95a47cba9fcc45d381144fb5c88bb/src/create_onnx_model)
